//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PYCRM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>@gmail.com</string>
  <string>@yahoo.in</string>
  <string>@outlook.com</string>
  <string>@getpy.biz</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EmailDomains {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailDomains"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Hindu</string>
  <string>Islamic</string>
  <string>Cristian</string>
  <string>Bhuddist</string>
  <string>Sikh</string>
  <string>Jain</string>
  <string>Ethist</string>
  <string>Other</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Ethnicity {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Ethnicity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Bengaluru</string>
  <string>Manipal</string>
  <string>Hubli</string>
  <string>Mangalore</string>
  <string>Gulbarga</string>
  <string>Davangere</string>
  <string>Mysore </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection City {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["City"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Andaman and Nicobar</string>
  <string>Andhra Pradesh</string>
  <string>Arunachal Pradesh</string>
  <string>Assam</string>
  <string>Bihar</string>
  <string>Chandigarh</string>
  <string>Chhattisgarh</string>
  <string>Dadra</string>
  <string>Daman</string>
  <string>Delhi</string>
  <string>Goa</string>
  <string>Gujarat</string>
  <string>Haryana</string>
  <string>Himachal</string>
  <string>Jammu</string>
  <string>Jharkhand</string>
  <string>Karnataka</string>
  <string>Kerala</string>
  <string>Lakshadweep</string>
  <string>Madhya Pradesh</string>
  <string>Maharashtra</string>
  <string>Manipur</string>
  <string>Meghalaya</string>
  <string>Mizoram</string>
  <string>Nagaland</string>
  <string>Odisha</string>
  <string>Pondicherry</string>
  <string>Punjab</string>
  <string>Rajasthan</string>
  <string>Sikkim</string>
  <string>Tamil</string>
  <string>Tripura</string>
  <string>Uttarakhand</string>
  <string>Uttar Pradesh</string>
  <string>West Bengal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection State {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["State"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>below 10</string>
  <string>10-15</string>
  <string>15-25</string>
  <string>25-40</string>
  <string>40-60</string>
  <string>60 above</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AgeGroup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AgeGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Male</string>\r\n  <string>Female</string>\r\n  <string>Other</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection Gender {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Gender"]));
            }
        }
    }
}
